import smtplib
import logging
import os
import pandas as pd
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

# 1. Logging Setup (Delivery Logs) 
logging.basicConfig(
    filename='email_delivery.log',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)

# 2. Sender Credentials
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "mahtabhussainofficial@gmail.com"        # Apna Gmail yahan likhein
SENDER_PASSWORD = "kguz ymjn fkca qopt" # 16-character App Password yahan likhein

def create_email(recipient_name, recipient_email, attachment_path=None):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Important Update for {recipient_name}"
    msg["From"] = SENDER_EMAIL
    msg["To"] = recipient_email

    # HTML Email Template (Personalized)
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px; }}
            .container {{ background-color: #ffffff; padding: 25px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
            h2 {{ color: #2c3e50; }}
            p {{ color: #555555; line-height: 1.6; font-size: 15px; }}
            .footer {{ margin-top: 20px; font-size: 12px; color: #888888; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h2>Assalam-o-Alaikum, {recipient_name}!</h2>
            <p>We are reaching out to confirm that your profile is successfully updated in our system.</p>
            <p>This is an automated notification generated by our Python Email Automation Engine.</p>
            <div class="footer">
                <hr>
                <p>Regards,<br><strong>Automation Team</strong></p>
            </div>
        </div>
    </body>
    </html>
    """
    msg.attach(MIMEText(html_content, "html"))

    # File Attachment Handling (Optional)
    if attachment_path and os.path.exists(attachment_path):
        filename = os.path.basename(attachment_path)
        with open(attachment_path, "rb") as attachment:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())
            encoders.encode_base64(part)
            part.add_header("Content-Disposition", f"attachment; filename= {filename}")
            msg.attach(part)

    return msg

def send_bulk_emails(csv_file_path, attachment_file=None):
    # CSV Data Read Karna via Pandas
    try:
        df = pd.read_csv(csv_file_path)
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return

    print(f"Starting email campaign for {len(df)} contacts...\n")

    # Connect to SMTP Server
    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()  # Secure connection (TLS)
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        print(" Connected to SMTP Server.\n")
    except Exception as e:
        print(f" SMTP Connection Failed: {e}")
        logging.error(f"SMTP Connection Failed: {e}")
        return

    # Loop through each recipient
    success_count = 0
    failure_count = 0

    for index, row in df.iterrows():
        name = row['name']
        email = row['email']

        msg = create_email(name, email, attachment_file)

        # Retry logic / Error Handling
        retries = 2
        sent = False

        for attempt in range(1, retries + 1):
            try:
                server.sendmail(SENDER_EMAIL, email, msg.as_string())
                print(f" Sent to {name} ({email})")
                logging.info(f"SUCCESS: Email sent to {name} <{email}>")
                success_count += 1
                sent = True
                break
            except Exception as e:
                print(f"Attempt {attempt} failed for {email}: {e}")
                if attempt == retries:
                    logging.error(f"FAILURE: Could not send to {name} <{email}>. Error: {e}")
                    failure_count += 1

    server.quit()
    print("\n Summary ")
    print(f"Total Sent: {success_count}")
    print(f"Failed:     {failure_count}")
    print("Check 'email_delivery.log' for complete logs.")

if __name__ == "__main__":
    print("Automated Email Dispatcher ")
    
    # Run bulk sending
    send_bulk_emails("recipients.csv")